import LocalizedStrings from "react-localization";

const strings = new LocalizedStrings({
  vi: {
    // Common
    appTitle: "Quản lý chung cư",
    appSubtitle: "Apartment Manager",
    loading: "Đang tải...",
    error: "Lỗi",
    success: "Thành công",
    cancel: "Hủy",
    save: "Lưu",
    edit: "Sửa",
    delete: "Xóa",
    confirm: "Xác nhận",
    back: "Quay lại",
    next: "Tiếp theo",
    previous: "Trước đó",
    yes: "Có",
    no: "Không",
    ok: "OK",
    close: "Đóng",
    search: "Tìm kiếm",
    filter: "Lọc",
    sort: "Sắp xếp",
    refresh: "Làm mới",
    export: "Xuất",
    import: "Nhập",
    print: "In",
    download: "Tải xuống",
    upload: "Tải lên",

    // Roles
    admin: "Quản trị viên",
    buildingManager: "Quản lý tòa nhà",
    resident: "Cư dân",
    security: "Bảo vệ",

    // Homepage
    homepageTitle: "PHẦN MỀM QUẢN LÝ",
    homepageSubtitle: "TÒA NHÀ THÔNG MINH",
    homepageDescription:
      "Hệ thống quản lý chung cư hiện đại với công nghệ AI, giúp tối ưu hóa vận hành và nâng cao trải nghiệm cư dân",

    // About Us Page
    aboutUsTitle: "VỀ DỰ ÁN NOAH",
    aboutUsSubtitle: "Giải pháp quản lý chung cư thông minh hàng đầu Việt Nam",
    aboutUsDescription:
      "Noah Smart Apartment Management là hệ thống quản lý chung cư hiện đại được phát triển với công nghệ AI tiên tiến, giúp tối ưu hóa vận hành và nâng cao trải nghiệm cư dân. Chúng tôi cam kết mang đến giải pháp toàn diện cho việc quản lý tòa nhà thông minh.",
    platformOverviewTitle: "TỔNG QUAN VỀ NỀN TẢNG CỦA CHÚNG TÔI",
    platformOverviewParagraph1:
      "Noah Smart Apartment Management là một nền tảng công nghệ tiên phong tại Việt Nam, được thiết kế để cách mạng hóa việc quản lý chung cư. Chúng tôi kết nối ban quản lý, cư dân và các nhà cung cấp dịch vụ trong một hệ sinh thái số hóa, mang lại sự tiện lợi, minh bạch và hiệu quả.",
    platformOverviewParagraph2:
      "Với sứ mệnh tạo ra môi trường sống hiện đại và an toàn, chúng tôi không ngừng cải tiến công nghệ để đáp ứng mọi nhu cầu của một tòa nhà thông minh. Từ việc quản lý tài chính đến bảo trì, an ninh và tương tác cộng đồng, Noah cung cấp một giải pháp toàn diện.",
    whatWeOfferTitle: "NHỮNG GÌ CHÚNG TÔI CUNG CẤP",
    offerItem1Title: "Quản lý toàn diện:",
    offerItem1Desc:
      "Hệ thống quản lý căn hộ, cư dân, tài chính và dịch vụ một cách hiệu quả.",
    offerItem2Title: "Công nghệ AI & IoT:",
    offerItem2Desc:
      "Tích hợp trí tuệ nhân tạo và Internet of Things để tự động hóa và tối ưu hóa vận hành.",
    offerItem3Title: "Bảo mật nâng cao:",
    offerItem3Desc:
      "Đảm bảo an toàn thông tin và dữ liệu với các lớp bảo mật tiên tiến.",
    offerItem4Title: "Trải nghiệm cư dân:",
    offerItem4Desc:
      "Cung cấp các tiện ích thông minh, giúp cư dân dễ dàng tương tác và sử dụng dịch vụ.",

    // Team Section
    teamTitle: "ĐỘI NGŨ SÁNG LẬP",
    teamSubtitle: "Các thành viên",
    teamMember1Name: "Trịnh Đình Ngọc",
    teamMember1Id: "HE171604",
    teamMember2Name: "Nguyễn Văn Dũng",
    teamMember2Id: "HE171465",
    teamMember3Name: "Nguyễn Quốc Thể",
    teamMember3Id: "HE171506",
    teamMember4Name: "Phạm Huy Tấn",
    teamMember4Id: "HE170915",
    teamMember5Name: "Trịnh Nguyễn Ngọc Anh",
    teamMember5Id: "HE171240",
    buildings: "Tòa nhà",
    residents: "Cư dân",
    uptime: "Uptime",
    experienceNow: "TRẢI NGHIỆM NGAY",
    learnMore: "TÌM HIỂU THÊM",
    features: "TÍNH NĂNG",
    about: "GIỚI THIỆU",
    contact: "LIÊN HỆ",
    home: "TRANG CHỦ",
    login: "ĐĂNG NHẬP",
    contactUs: "Liên Hệ Chúng Tôi",
    phone: "0369686293",
    email: "anhtnnhe171240@fpt.edu.vn",
    logout: "Đăng xuất",

    // Footer
    companyName: "Noah Smart Apartment Management",
    companyDescription:
      "Hệ thống quản lý chung cư thông minh hàng đầu Việt Nam",
    address: "Xã Thạch Hòa, TP. Hà Nội",
    businessHours: "Thứ 2 - Thứ 6: 8:00 - 17:30",
    weekendHours: "Thứ 7: 8:00 - 12:00",
    quickLinks: "Liên kết nhanh",
    aboutUs: "Về chúng tôi",
    services: "Dịch vụ",
    support: "Hỗ trợ",
    privacy: "Chính sách bảo mật",
    terms: "Điều khoản sử dụng",
    followUs: "Theo dõi chúng tôi",
    allRightsReserved:
      "© 2024 Noah Smart Apartment Management. Tất cả quyền được bảo lưu.",

    // Features Section
    featuredFeatures: "TÍNH NĂNG NỔI BẬT",
    apartmentManagement: "Quản lý căn hộ",
    apartmentManagementDesc:
      "Theo dõi trạng thái, thông tin chi tiết từng căn hộ",
    residentManagement: "Quản lý cư dân",
    residentManagementDesc:
      "Hồ sơ cư dân, thông tin liên hệ, lịch sử giao dịch",
    smartServices: "Dịch vụ thông minh",
    smartServicesDesc: "Tích hợp AI, tự động hóa quy trình quản lý",
    securitySystem: "Hệ thống an ninh",
    securitySystemDesc: "Giám sát 24/7, kiểm soát ra vào thông minh",
    financialManagement: "Quản lý tài chính",
    financialManagementDesc: "Thu phí, báo cáo tài chính, thanh toán online",
    maintenanceSystem: "Hệ thống bảo trì",
    maintenanceSystemDesc:
      "Lên lịch bảo trì, theo dõi sự cố, báo cáo tình trạng",

    // About Section
    aboutTitle: "VỀ DỰ ÁN NOAH",
    aboutSubtitle: "Giải pháp quản lý chung cư thông minh hàng đầu Việt Nam",
    aboutDescription:
      "Noah Smart Apartment Management là hệ thống quản lý chung cư hiện đại được phát triển với công nghệ AI tiên tiến, giúp tối ưu hóa vận hành và nâng cao trải nghiệm cư dân. Chúng tôi cam kết mang đến giải pháp toàn diện cho việc quản lý tòa nhà thông minh.",
    ourMission: "Sứ mệnh của chúng tôi",
    ourMissionDesc:
      "Tạo ra một hệ sinh thái quản lý chung cư thông minh, kết nối mọi người và tối ưu hóa cuộc sống đô thị hiện đại.",
    ourVision: "Tầm nhìn",
    ourVisionDesc:
      "Trở thành nền tảng quản lý chung cư thông minh hàng đầu Đông Nam Á, góp phần xây dựng các thành phố thông minh bền vững.",
    whyChooseUs: "Tại sao chọn Noah?",
    technology: "Công nghệ tiên tiến",
    technologyDesc:
      "Sử dụng AI, IoT và Big Data để tối ưu hóa quy trình quản lý",
    experience: "Kinh nghiệm chuyên sâu",
    experienceDesc: "Hơn 5 năm kinh nghiệm trong lĩnh vực quản lý bất động sản",
    support24: "Hỗ trợ 24/7",
    support24Desc: "Đội ngũ chuyên gia sẵn sàng hỗ trợ mọi lúc, mọi nơi",
    securityAbsolute: "Bảo mật tuyệt đối",
    securityAbsoluteDesc: "Hệ thống bảo mật đa lớp, đảm bảo an toàn thông tin",

    // Stats Section
    ourAchievements: "THÀNH TỰU CỦA CHÚNG TÔI",
    projectsCompleted: "Dự án hoàn thành",
    happyResidents: "Cư dân hài lòng",
    buildingsManaged: "Tòa nhà quản lý",
    yearsExperience: "Năm kinh nghiệm",

    // Technology Section
    technologyTitle: "CÔNG NGHỆ TIÊN TIẾN",
    technologySubtitle: "Sức mạnh của AI và IoT trong quản lý chung cư",
    aiPowered: "AI-Powered",
    aiPoweredDesc: "Trí tuệ nhân tạo giúp dự đoán và tối ưu hóa quy trình",
    iotIntegration: "Tích hợp IoT",
    iotIntegrationDesc: "Kết nối mọi thiết bị thông minh trong tòa nhà",
    cloudBased: "Nền tảng đám mây",
    cloudBasedDesc: "Truy cập mọi lúc, mọi nơi với độ bảo mật cao",
    mobileFirst: "Mobile-First",
    mobileFirstDesc: "Giao diện tối ưu cho mọi thiết bị di động",

    // Login
    loginTitle: "Noah Smart Apartment Management",
    emailLabel: "Email",
    emailPlaceholder: "Nhập email của bạn",
    password: "Mật khẩu",
    passwordPlaceholder: "Nhập mật khẩu của bạn",
    role: "Vai trò",
    loginButton: "Đăng nhập",
    loginSuccess: "Đăng nhập thành công",
    loggingIn: "Đang đăng nhập...",
    backToHomepage: "Quay lại Trang chủ",
    noAccount: "Chưa có tài khoản?",
    signupNow: "Đăng ký ngay",
    forgotPassword: "Quên mật khẩu?",
    passwordToggle: {
      show: "Hiện mật khẩu",
      hide: "Ẩn mật khẩu",
    },
    errors: {
      emailRequired: "Vui lòng nhập email",
      passwordRequired: "Vui lòng nhập mật khẩu",
      passwordMinLength: "Mật khẩu phải có ít nhất 6 ký tự",
      invalidCredentials: "Email, mật khẩu hoặc vai trò không đúng",
      loginFailed: "Đăng nhập thất bại",
    },
    roles: {
      buildingManager: "Quản lý tòa nhà",
      resident: "Cư dân",
      admin: "Quản trị viên",
      security: "Bảo vệ",
    },

    // Dashboard
    dashboardSubtitle: "Tổng quan quản lý khu",
    totalBuildings: "Tổng tòa nhà",
    totalApartments: "Tổng căn hộ",
    residentsCount: "Cư dân",
    occupancyRate: "Tỷ lệ lấp đầy",
    maintenanceRequests: "Yêu cầu bảo trì",
    pendingTickets: "Ticket chờ xử lý",
    securityAlerts: "Cảnh báo an ninh",
    monthlyRevenue: "Doanh thu tháng",
    monthlyRevenueChart: "Doanh thu theo tháng",
    occupancyByBuilding: "Tỷ lệ lấp đầy các tòa",
    buildingA: "Tòa A",
    buildingB: "Tòa B",
    buildingC: "Tòa C",
    recentActivities: "Yêu cầu gần đây",
    alerts: "Lịch bảo trì sắp tới",

    // Navigation
    dashboard: "Bảng điều khiển",
    announcements: "Quản lý thông báo",
    floors: "Quản lý tầng",
    buildingsManagement: "Quản lý tòa nhà",
    apartments: "Quản lý căn hộ",
    amenities: "Quản lý tiện ích",
    cards: "Quản lý thẻ",
    assets: "Quản lý tài sản",
    assetsManagement: "Quản lý Tài sản",
    assetsDescription: "Quản lý và theo dõi tất cả tài sản chung cư",
    fees: "Quản lý phí",
    reports: "Báo cáo",
    settings: "Cài đặt",
    myApartment: "Căn hộ của tôi",
    serviceRequests: "Yêu cầu dịch vụ",

    // Admin specific
    adminDashboard: "Bảng điều khiển Admin",
    adminDashboardSubtitle: "Tổng quan hệ thống & Quản lý",
    userManagement: "Quản lý người dùng",
    buildingManagers: "Quản lý tòa nhà",
    securityStaff: "Nhân viên bảo vệ",
    activeServices: "Thẻ hoạt động",
    systemPerformance: "Hiệu suất hệ thống",
    systemOverview: "Tổng quan hệ thống",
    userActivity: "Hoạt động người dùng",
    buildingPerformance: "Hiệu suất tòa nhà",
    financialSummary: "Tóm tắt tài chính",
    securityReports: "Báo cáo an ninh",
    systemSettings: "Cài đặt hệ thống",
    totalUsers: "Tổng người dùng",
    activeBuildings: "Tòa nhà hoạt động",
    totalRevenue: "Tổng doanh thu",
    systemUptime: "Thời gian hoạt động",
    generateReport: "Tạo báo cáo",
    exportPDF: "Xuất PDF",
    exportExcel: "Xuất Excel",
    addNew: "Thêm mới",
    addNewBuilding: "Thêm tòa nhà mới",
    viewDetails: "Xem chi tiết",
    averageOccupancy: "Tỷ lệ lấp đầy trung bình",
    generalSettings: "Cài đặt chung",
    securitySettings: "Cài đặt bảo mật",
    notificationSettings: "Cài đặt thông báo",
    systemSettingsTitle: "Cài đặt hệ thống",
    siteName: "Tên trang web",
    siteDescription: "Mô tả trang web",
    timezone: "Múi giờ",
    defaultLanguage: "Ngôn ngữ mặc định",
    minimumPasswordLength: "Độ dài mật khẩu tối thiểu",
    sessionTimeout: "Thời gian chờ phiên",
    enableTwoFactorAuth: "Bật xác thực hai yếu tố",
    maxLoginAttempts: "Số lần đăng nhập tối đa",
    emailNotifications: "Thông báo email",
    smsNotifications: "Thông báo SMS",
    pushNotifications: "Thông báo đẩy",
    maintenanceAlerts: "Cảnh báo bảo trì",
    maintenanceMode: "Chế độ bảo trì",
    automaticBackup: "Sao lưu tự động",
    logLevel: "Mức độ ghi log",
    maxFileSize: "Kích thước file tối đa",
    saveChanges: "Lưu thay đổi",
    resetToDefault: "Đặt lại mặc định",
  },

  en: {
    // Common
    appTitle: "Apartment Management",
    appSubtitle: "Smart Building System",
    loading: "Loading...",
    error: "Error",
    success: "Success",
    cancel: "Cancel",
    save: "Save",
    edit: "Edit",
    delete: "Delete",
    confirm: "Confirm",
    back: "Back",
    next: "Next",
    previous: "Previous",
    yes: "Yes",
    no: "No",
    ok: "OK",
    close: "Close",
    search: "Search",
    filter: "Filter",
    sort: "Sort",
    refresh: "Refresh",
    export: "Export",
    import: "Import",
    print: "Print",
    download: "Download",
    upload: "Upload",

    // Roles
    admin: "Administrator",
    buildingManager: "Building Manager",
    resident: "Resident",
    security: "Security",

    // Homepage
    homepageTitle: "SMART BUILDING",
    homepageSubtitle: "MANAGEMENT SOFTWARE",
    homepageDescription:
      "Modern apartment management system with AI technology, helping to optimize operations and enhance resident experience",

    // About Us Page
    aboutUsTitle: "ABOUT NOAH PROJECT",
    aboutUsSubtitle: "Vietnam's leading smart apartment management solution",
    aboutUsDescription:
      "Noah Smart Apartment Management is a modern apartment management system developed with advanced AI technology, helping to optimize operations and enhance resident experience. We are committed to providing comprehensive solutions for smart building management.",
    platformOverviewTitle: "PLATFORM OVERVIEW",
    platformOverviewParagraph1:
      "Noah Smart Apartment Management is a pioneering technology platform in Vietnam, designed to revolutionize apartment management. We connect management boards, residents, and service providers in a digitized ecosystem, bringing convenience, transparency, and efficiency.",
    platformOverviewParagraph2:
      "With a mission to create a modern and safe living environment, we continuously innovate technology to meet all the needs of a smart building. From financial management to maintenance, security, and community interaction, Noah provides a comprehensive solution.",
    whatWeOfferTitle: "WHAT WE OFFER",
    offerItem1Title: "Comprehensive Management:",
    offerItem1Desc:
      "Efficiently manage apartments, residents, finances, and services.",
    offerItem2Title: "AI & IoT Technology:",
    offerItem2Desc:
      "Integrate artificial intelligence and the Internet of Things to automate and optimize operations.",
    offerItem3Title: "Advanced Security:",
    offerItem3Desc:
      "Ensure information and data security with advanced security layers.",
    offerItem4Title: "Enhanced Resident Experience:",
    offerItem4Desc:
      "Provide smart utilities, making it easy for residents to interact and use services.",

    // Team Section
    teamTitle: "FOUNDING TEAM",
    teamSubtitle: "Members",
    teamMember1Name: "Trinh Đinh Ngoc",
    teamMember1Id: "HE171604",
    teamMember2Name: "Nguyen Van Dung",
    teamMember2Id: "HE171465",
    teamMember3Name: "Nguyen Quoc The",
    teamMember3Id: "HE171506",
    teamMember4Name: "Pham Huy Tan",
    teamMember4Id: "HE170915",
    teamMember5Name: "Trinh Nguyen Ngoc Anh",
    teamMember5Id: "HE171240",
    buildings: "Buildings",
    residents: "Residents",
    uptime: "Uptime",
    experienceNow: "EXPERIENCE NOW",
    learnMore: "LEARN MORE",
    features: "FEATURES",
    about: "ABOUT",
    contact: "CONTACT",
    home: "HOME",
    login: "LOGIN",
    contactUs: "Contact Us",
    phone: "0369686293",
    email: "anhtnnhe171240@fpt.edu.vn",
    logout: "Logout",

    // Footer
    companyName: "Noah Smart Apartment Management",
    companyDescription: "Vietnam's leading smart apartment management system",
    address: " Thach Hoa Communal, Ha Noi City",
    businessHours: "Monday - Friday: 8:00 AM - 5:30 PM",
    weekendHours: "Saturday: 8:00 AM - 12:00 PM",
    quickLinks: "Quick Links",
    aboutUs: "About Us",
    services: "Card Management",
    support: "Support",
    privacy: "Privacy Policy",
    terms: "Terms of Service",
    followUs: "Follow Us",
    allRightsReserved:
      "© 2024 Noah Smart Apartment Management. All rights reserved.",

    // Features Section
    featuredFeatures: "FEATURED FEATURES",
    apartmentManagement: "Apartment Management",
    apartmentManagementDesc:
      "Track status and detailed information for each apartment",
    residentManagement: "Resident Management",
    residentManagementDesc:
      "Resident profiles, contact information, transaction history",
    smartServices: "Smart Services",
    smartServicesDesc: "AI integration, automated management processes",
    securitySystem: "Security System",
    securitySystemDesc: "24/7 monitoring, smart access control",
    financialManagement: "Financial Management",
    financialManagementDesc:
      "Fee collection, financial reports, online payments",
    maintenanceSystem: "Maintenance System",
    maintenanceSystemDesc: "Schedule maintenance, track issues, status reports",

    // About Section
    aboutTitle: "ABOUT NOAH PROJECT",
    aboutSubtitle: "Vietnam's leading smart apartment management solution",
    aboutDescription:
      "Noah Smart Apartment Management is a modern apartment management system developed with advanced AI technology, helping to optimize operations and enhance resident experience. We are committed to providing comprehensive solutions for smart building management.",
    ourMission: "Our Mission",
    ourMissionDesc:
      "Create a smart apartment management ecosystem that connects people and optimizes modern urban life.",
    ourVision: "Our Vision",
    ourVisionDesc:
      "Become Southeast Asia's leading smart apartment management platform, contributing to building sustainable smart cities.",
    whyChooseUs: "Why Choose Noah?",
    technology: "Advanced Technology",
    technologyDesc:
      "Using AI, IoT and Big Data to optimize management processes",
    experience: "Deep Experience",
    experienceDesc: "Over 5 years of experience in real estate management",
    support24: "24/7 Support",
    support24Desc: "Expert team ready to support anytime, anywhere",
    securityAbsolute: "Absolute Security",
    securityAbsoluteDesc:
      "Multi-layer security system ensuring information safety",

    // Stats Section
    ourAchievements: "OUR ACHIEVEMENTS",
    projectsCompleted: "Projects Completed",
    happyResidents: "Happy Residents",
    buildingsManaged: "Buildings Managed",
    yearsExperience: "Years Experience",

    // Technology Section
    technologyTitle: "ADVANCED TECHNOLOGY",
    technologySubtitle: "The power of AI and IoT in apartment management",
    aiPowered: "AI-Powered",
    aiPoweredDesc:
      "Artificial intelligence helps predict and optimize processes",
    iotIntegration: "IoT Integration",
    iotIntegrationDesc: "Connect all smart devices in the building",
    cloudBased: "Cloud Platform",
    cloudBasedDesc: "Access anytime, anywhere with high security",
    mobileFirst: "Mobile-First",
    mobileFirstDesc: "Interface optimized for all mobile devices",

    // Login
    loginTitle: "Noah Smart Apartment Management",
    loginSubtitle: "Login to the smart management system",
    emailLabel: "Email",
    emailPlaceholder: "Enter your email",
    password: "Password",
    passwordPlaceholder: "Enter your password",
    role: "Role",
    loginButton: "Login",
    loginSuccess: "Login successful",
    loggingIn: "Logging in...",
    backToHomepage: "Back to Homepage",
    noAccount: "Don't have an account?",
    signupNow: "Sign up now",
    forgotPassword: "Forgot password?",
    passwordToggle: {
      show: "Show password",
      hide: "Hide password",
    },
    errors: {
      emailRequired: "Please enter email",
      passwordRequired: "Please enter password",
      passwordMinLength: "Password must be at least 6 characters",
      invalidCredentials: "Invalid email, password or role",
      loginFailed: "Login failed",
    },
    roles: {
      buildingManager: "Building Manager",
      resident: "Resident",
      admin: "Administrator",
      security: "Security",
    },

    // Dashboard
    dashboardSubtitle: "Building Management Overview",
    totalBuildings: "Total Buildings",
    totalApartments: "Total Apartments",
    residentsCount: "Residents",
    occupancyRate: "Occupancy Rate",
    maintenanceRequests: "Maintenance Requests",
    pendingTickets: "Pending Tickets",
    securityAlerts: "Security Alerts",
    monthlyRevenue: "Monthly Revenue",
    monthlyRevenueChart: "Monthly Revenue",
    occupancyByBuilding: "Occupancy Rate by Building",
    buildingA: "Building A",
    buildingB: "Building B",
    buildingC: "Building C",
    recentActivities: "Recent Requests",
    alerts: "Upcoming Maintenance",

    // Navigation
    dashboard: "Dashboard",
    announcements: "Announcements Management",
    floors: "Floor Management",
    buildingsManagement: "Building Management",
    apartments: "Apartment Management",
    amenities: "Amenities Management",
    residentsManagement: "Resident Management",
    cards: "Card Management",
    assets: "Asset Management",
    assetsManagement: "Asset Management",
    assetsDescription: "Manage and track all building assets",
    fees: "Fee Management",
    reports: "Reports",
    settings: "Settings",
    myApartment: "My Apartment",
    serviceRequests: "Service Requests",

    // Admin specific
    adminDashboard: "Admin Dashboard",
    adminDashboardSubtitle: "System Overview & Management",
    userManagement: "User Management",
    buildingManagers: "Building Managers",
    securityStaff: "Security Staff",
    activeServices: "Active Services",
    systemPerformance: "System Performance",
    systemOverview: "System Overview",
    userActivity: "User Activity",
    buildingPerformance: "Building Performance",
    financialSummary: "Financial Summary",
    securityReports: "Security Reports",
    systemSettings: "System Settings",
    totalUsers: "Total Users",
    activeBuildings: "Active Buildings",
    totalRevenue: "Total Revenue",
    systemUptime: "System Uptime",
    generateReport: "Generate Report",
    exportPDF: "Export PDF",
    exportExcel: "Export Excel",
    addNew: "Add New",
    addNewBuilding: "Add New Building",
    viewDetails: "View Details",
    averageOccupancy: "Average Occupancy",
    generalSettings: "General Settings",
    securitySettings: "Security Settings",
    notificationSettings: "Notification Settings",
    systemSettingsTitle: "System Settings",
    siteName: "Site Name",
    siteDescription: "Site Description",
    timezone: "Timezone",
    defaultLanguage: "Default Language",
    minimumPasswordLength: "Minimum Password Length",
    sessionTimeout: "Session Timeout",
    enableTwoFactorAuth: "Enable Two-Factor Authentication",
    maxLoginAttempts: "Max Login Attempts",
    emailNotifications: "Email Notifications",
    smsNotifications: "SMS Notifications",
    pushNotifications: "Push Notifications",
    maintenanceAlerts: "Maintenance Alerts",
    maintenanceMode: "Maintenance Mode",
    automaticBackup: "Automatic Backup",
    logLevel: "Log Level",
    maxFileSize: "Max File Size",
    saveChanges: "Save Changes",
    resetToDefault: "Reset to Default",
  },
});

export default strings;
